### PR TITLE
Fixes GitHub Pages Deploy

### LINKED ISSUE #15: Fix Web App Deployment Pipeline

### PR DESCRIPTION
**Pull request by ishchow**
Fixes #15

### CODE REVIEW

**Comment by ishchow** [comment]
See https://github.com/ECE-492-W2020-Group-6/smart-blinds-webapp/actions for logs of previous successful builds with these changes.

I didn't try to make a meaningful change to the website yet since I don't really know how to modify a react project but I think it should work.

**Comment by ishchow** [comment]
I made some changes to test if the deploy actually works.

This was what the deployed site looks like before the changes:

before-deploy

This is what the deployed site looks after the changes:

after-deploy

Note: I'm using dark mode in my browser, I didn't change the colorscheme of the app.

So I've fully tested this now.

**Comment by ishchow** [comment]
After this is pushed to master, the deployed site should look like my first screenshot since I've removed my test changes and rebased this branch.

**Comment by kdehaan** [comment]
Nice!

**Pull request merged**
